server:
  port: 8082

spring:
  datasource:
    url: jdbc:postgresql://localhost:5434/publications_db
    username: publications_user
    password: publications_pass
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

# URL base de tu authors-service (t√∫ usas 8081)
authors:
  base-url: http://localhost:8081
